import React, { useState, useEffect } from 'react';
import { Typography, Paper, Grid, Box, Button, IconButton, TextField } from '@mui/material';
import { 
  InsertDriveFileOutlined,
  MoreHoriz,
  Logout,
  History,
  Settings,
  Stars 
} from '@mui/icons-material';

export default function Dashboard() {
  const [files, setFiles] = useState([]);
  const [activeTab, setActiveTab] = useState('history'); 

  useEffect(() => {
    // replace with fetch() call
    const mockFiles = [
      {
        name: 'Sample_file.pdf',
        date: 'September 30, 2025',
        url: '/404'
      },
      {
        name: 'Sample_file_2.jpg',
        date: 'October 6, 2025',
        url: '/404'
      }
    ];
    setFiles(mockFiles);
  }, []);

  const handleOpenFile = (file) => {
    window.open(file.url, '_blank');
  };

  //needs backend. get user's conversations
  const previous = [
    'Sample title 1',
    'Sample title 2',
    'Sample title 3',
    'Sample title 4',
    'Sample title 5',
    'Sample title 6',
    'Sample title 7',
    'Sample title 8',
    'Sample title 9'
  ];

  const renderContent = () => {
    switch (activeTab) {  
      case 'history':  // activeTab by using cases, sample code generated by AI
        return (
          <Box 
            sx={{ 
              height: '100%', 
              display: 'flex', 
              flexDirection: 'column' 
            }}>
            <Typography
              sx={{
                fontWeight: 800,
                fontSize: 34,
                mb: 4
              }}
            >
              Previous Chat
            </Typography>
              <Box sx={{ flexGrow: 1, overflowY: 'auto' }}>
                {previous.map((t, i) => (
                <Paper
                  key={i}
                  sx={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    px: 2,
                    py: 1,
                    border: '1.5px solid #000',
                    borderRadius: 2,
                    boxShadow: '2px 2px 0 #00000020',
                    mb: 1
                  }}
                >
                  <Typography sx={{ fontSize: 14 }}>{t}</Typography>
                  {/* needs backend. edit/delete options */}
                  <IconButton size='small' sx={{ color: '#000' }}>
                  <MoreHoriz />
                  </IconButton>
                </Paper>
              ))}
            </Box>
          </Box>
        );
      
      case 'documents':
        return (
          <Box>
            <Typography
              sx={{
                fontWeight: 800,
                fontSize: 34,
                mb: 4
              }}
            >
              Recent Documents
            </Typography>

            <Grid container spacing={3}>
              {files.map((file, i) => (
                <Grid item key={i}>
                  <Paper
                    onClick={() => handleOpenFile(file)}
                    sx={{
                      width: 160,
                      height: 160,
                      border: '1.5px solid #000',
                      borderRadius: 3,
                      p: 2,
                      boxShadow: '3px 3px 0 rgba(0,0,0,0.15)',
                      display: 'flex',
                      flexDirection: 'column',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      cursor: 'pointer'
                    }}
                  >
                    <Box sx={{ textAlign: 'center', mt: 2 }}>
                      <InsertDriveFileOutlined sx={{ fontSize: 50 }} />
                    </Box>
                    <Box
                      sx={{
                        borderTop: '1px solid #000',
                        width: '100%',
                        mt: 2,
                        pt: 1,
                        textAlign: 'center',
                        position: 'relative'
                      }}
                    >
                      <Typography  // file name restriction generated by AI 
                        sx={{ 
                          fontSize: 14, 
                          fontWeight: 500,
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                          width: '100%',
                          px: 0.5 
                        }} 
                      >
                        {file.name.length > 20 ? `${file.name.substring(0, 20)}...` : file.name }
                      </Typography>
                      
                      <Typography sx={{ fontSize: 12, color: '#555' }}>
                        {file.date}
                      </Typography>
                      <MoreHoriz
                        sx={{
                          position: 'absolute',
                          right: 4,
                          top: -30,
                          fontSize: 22,
                          color: '#000'
                        }}
                      />
                    </Box>
                  </Paper>
                </Grid>
              ))}
            </Grid>

            <Button
              onClick={() => window.location.href = '/documents'}
              sx={{
                textTransform: 'none',
                textDecoration: 'underline',
                fontWeight: 800,
                color: '#000',
                mt: 1,
                mb: 2,
                '&:hover': {
                  backgroundColor: 'transparent', 
                  textDecoration: 'underline', 
                },
              }}
            >
              View All Documents
            </Button>
          </Box>
        );
      
      case 'settings':
        return (
          //needs backend
          <Box>
            <Typography
              sx={{
                fontWeight: 800,
                fontSize: 34,
                mb: 4
              }}
            >
              Settings - Reset Your Password
            </Typography>
            <Box
              sx={{
                display: 'flex',
                flexDirection: 'column', 
                alignItems: 'flex-start', 
                justifyContent: 'center'
             }}
            >
              <Typography sx={{ fontWeight: 400, fontSize: 20 }}>
                Enter your current password
              </Typography>
              <TextField
                fullWidth
                type='password'
                variant='outlined'
                margin='normal'
              />
              <Typography sx={{ fontWeight: 400, fontSize: 20 }}>
                Enter your new password
              </Typography>
              <TextField
                fullWidth
                type='password'
                variant='outlined'
                margin='normal'
              />
              <Typography sx={{ fontWeight: 400, fontSize: 20 }}>
                Re-enter your new password
              </Typography>
              <TextField
                fullWidth
                type='password'
                variant='outlined'
                margin='normal'
              />
            </Box>
            <Button
              variant='contained'
              size='large'
              sx={{ 
                textTransform: 'none',
                backgroundColor: 'black', 
                fontSize: 20,
                mt: 2 
              }}
            >
              Confirm your change
            </Button>
          </Box>
        );

      default:
        return null;
    }
  };

  const DashboardSidebar = (
    <>
      <Box>
        <Box 
          sx={{ 
           display: 'flex',
           alignItems: 'center',
           justifyContent: 'flex-start',
           mb: 6 
          }}
        >
          <Stars sx={{ fontSize: 30, mr: 1 }}/>
          <Typography 
            variant='h5'
            component='h1'
            sx={{ fontWeight: 'bold' }}
          >
            Dashboard
          </Typography>
        </Box>

        <Box sx={{ borderBottom: '1px solid #000', my: 2 }} />

        <Button
          fullWidth
          startIcon={<History />}
          variant={activeTab === 'history' ? 'contained' : 'outlined'}
          onClick={() => setActiveTab('history')}
          sx={{
            border: '1.2px solid #000',
            borderRadius: 2,
            fontWeight: 600,
            textTransform: 'none',
            color: '#000',
            mb: 1.2,
            bgcolor: activeTab === 'history' ? '#ddd' : '#f3f3f3ff',
            boxShadow: '2px 2px 0 rgba(0,0,0,0.15)',
            '&:hover': { bgcolor: activeTab === 'history' ? '#ddd' : '#f8f8f8' },
            justifyContent: 'flex-start',
            pl: 2
          }}
        >
          Chat History
        </Button>

        <Button
          fullWidth
          startIcon={<InsertDriveFileOutlined />}
          variant={activeTab === 'documents' ? 'contained' : 'outlined'}
          onClick={() => setActiveTab('documents')}
          sx={{
            border: '1.2px solid #000',
            borderRadius: 2,
            fontWeight: 600,
            textTransform: 'none',
            color: '#000',
            mb: 1.2,
            bgcolor: activeTab === 'documents' ? '#ddd' : '#f3f3f3ff',
            boxShadow: '2px 2px 0 rgba(0,0,0,0.15)',
            '&:hover': { bgcolor: activeTab === 'documents' ? '#ddd' : '#f8f8f8' },
            justifyContent: 'flex-start',
            pl: 2
          }}
        >
          Documents
        </Button>

        <Button
          fullWidth
          startIcon={<Settings />}
          variant={activeTab === 'settings' ? 'contained' : 'outlined'}
          onClick={() => setActiveTab('settings')}
          sx={{
            border: '1.2px solid #000',
            borderRadius: 2,
            fontWeight: 600,
            textTransform: 'none',
            color: '#000',
            mb: 1.2,
            bgcolor: activeTab === 'settings' ? '#ddd' : '#f3f3f3ff',
            boxShadow: '2px 2px 0 rgba(0,0,0,0.15)',
            '&:hover': { bgcolor: activeTab === 'settings' ? '#ddd' : '#f8f8f8' },
            justifyContent: 'flex-start',
            pl: 2
          }}
        >
          Settings
        </Button>
      </Box>
      
      <Box>
        <Button
          fullWidth
          variant='outlined'
          onClick={() => window.location.href = '/chat/:docId'}
          sx={{
            border: '1.2px solid #000',
            borderRadius: 2,
            fontWeight: 600,
            textTransform: 'none',
            color: '#000',
            mt: 1,
            mb: 2,
            boxShadow: '2px 2px 0 rgba(0,0,0,0.15)',
            '&:hover': { bgcolor: '#f8f8f8' }
          }}
        >
          Back to Chatbot
        </Button>
      
        <Box
          sx={{
            display: 'flex',
            alignItems: 'center',
            gap: 1,
            px: 0.5
          }}
        >
          <Paper
              sx={{
                width: 34,
                height: 34,
                borderRadius: '50%',
                border: '1px solid #000',
                display: 'flex',                  
                alignItems: 'center',
                justifyContent: 'center',
                fontWeight: 600,
                bgcolor: '#fff'
              }}
            >
              U
          </Paper>
          <Typography sx={{ fontWeight: 600 }}>User</Typography>
          <Box sx={{ flex: 1 }} />
          <Logout sx={{ fontSize: 20 }} />
        </Box>          
      </Box>
    </>
  );

  return (
    <Box 
      sx={{ 
        display: 'flex', 
        height: '100vh', 
        bgcolor: '#fff', 
        color: '#000', 
        overflow: 'hidden' 
      }}>
      <Box
        sx={{
          width: 240,
          borderRight: '1.5px solid #000',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          p: 2.2
        }}
      >
        {DashboardSidebar}
      </Box>

      <Box sx={{ flex: 1, p: 5, overflow: 'auto' }}>
        {renderContent()}
      </Box>
    </Box>
  );
}